
**1 import Libraries**

In [2]:
import numpy as np
import pandas as pd

**2 Read dataset from drive or your device**

In [ ]:
'''# from google drive

from google.colab import drive
drive.mount('/content/drive')
'''

Mounted at /content/drive

In [ ]:
'''
data=pd.read_csv("/content/drive/MyDrive/Machine Learning_CODE    /Data_Preprocessing/Data.csv")
data.head()
'''

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

# Data Preprocessing Tutorial

### First let's import our dataset

In [ ]:
df = pd.read_csv('unprocessed_data.csv')
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [ ]:

y= df['Purchased']
X=df.drop(['Purchased'],1)
X

<ipython-input-56-63b2d219d301>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X=df.drop(['Purchased'],1)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

## Start with First Column its Categorical so Lets Turn it into  Dummies

In [ ]:

X=pd.get_dummies(X)
X

    Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0               1                0              0
1  27.0  48000.0               0                0              1
2  30.0  54000.0               0                1              0
3  38.0  61000.0               0                0              1
4  40.0      NaN               0                1              0
5  35.0  58000.0               1                0              0
6   NaN  52000.0               0                0              1
7  48.0  79000.0               1                0              0
8  50.0  83000.0               0                1              0
9  37.0  67000.0               1                0              0

## Handling the missing data
 we have two options :
 1. remove the row
 It can be done easily through excel or pandas or numpy by slicing
 2. replace it by the mean
 It also can be done with many ways but lets use Imputer

In [ ]:
missing=df.isnull().sum()
print(missing)

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [ ]:
missing_prec=100*df.isnull().sum()/len(df)
missing_prec

Country       0.0
Age          10.0
Salary       10.0
Purchased     0.0
dtype: float64

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values= np.nan, strategy='mean')

X = imputer.fit_transform(X.values)
X

array([[4.40000000e+01, 7.20000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [2.70000000e+01, 4.80000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00],
       [3.00000000e+01, 5.40000000e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [3.80000000e+01, 6.10000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00],
       [4.00000000e+01, 6.37777778e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [3.50000000e+01, 5.80000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.87777778e+01, 5.20000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00],
       [4.80000000e+01, 7.90000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [5.00000000e+01, 8.30000000e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [3.70000000e+01, 6.70000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00]])

In [ ]:

X=X.astype(int)
X

array([[   44, 72000,     1,     0,     0],
       [   27, 48000,     0,     0,     1],
       [   30, 54000,     0,     1,     0],
       [   38, 61000,     0,     0,     1],
       [   40, 63777,     0,     1,     0],
       [   35, 58000,     1,     0,     0],
       [   38, 52000,     0,     0,     1],
       [   48, 79000,     1,     0,     0],
       [   50, 83000,     0,     1,     0],
       [   37, 67000,     1,     0,     0]])

## Handling Binary Categories

In [ ]:
# import the needed librarys
#to Deal with Categorical Label
from sklearn.preprocessing import LabelEncoder
print(y)
encoder = LabelEncoder()
label_vector = encoder.fit_transform(y)
label_vector

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])